name: Setup ROS 2 Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python3-venv package
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.8-venv

      - name: Set up virtual environment
        run: |
          python3 -m venv ros2_env
          source ros2_env/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
